package enums;

public enum TipoMovimentoDaPeca {
    HORIZONTAL,
    VERTICAL,
    VERTICAL_CIMA,
    VERTICAL_BAIXO,
    DIAGONAL_ESQUERDA_PARA_DIREITA,
    DIAGONAL_DIREITA_PARA_ESQUERDA,
    MOVIMENTO_EM_L,
    MOVIMENTO_DO_REI;


}
